// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onBackWardChange();
void onForWardChange();
void onLeFtChange();
void onRiGhtChange();

bool backWard;
bool forWard;
bool leFt;
bool riGht;

void initProperties(){

  ArduinoCloud.addProperty(backWard, READWRITE, ON_CHANGE, onBackWardChange);
  ArduinoCloud.addProperty(forWard, READWRITE, ON_CHANGE, onForWardChange);
  ArduinoCloud.addProperty(leFt, READWRITE, ON_CHANGE, onLeFtChange);
  ArduinoCloud.addProperty(riGht, READWRITE, ON_CHANGE, onRiGhtChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
